# Generated by Django 5.2 on 2025-05-13 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Надпись на кнопке')),
                ('style', models.CharField(blank=True, max_length=255, verbose_name='CSS-класс / стиль')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='internships.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Кнопка блока',
                'verbose_name_plural': 'Кнопки блока',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blocks/images/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='internships.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Изображение блока',
                'verbose_name_plural': 'Изображения блока',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='internships.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Текст блока',
                'verbose_name_plural': 'Тексты блока',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='blocks/videos/previews/', verbose_name='Превью видео')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='internships.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Видео блока',
                'verbose_name_plural': 'Видео блока',
            },
        ),
    ]
